---
title: "Exploratory Data Analysis"
subtitle: "Understanding Data and their Environment - MSc Data Science"
author: "11549067"
output: 
  pdf_document: 
    latex_engine: xelatex 
    extra_dependencies: ["helvet"]
---

```{r}
library(rio)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
library(hexbin)
library(ggrepel)
```

```{r}
data = import("/Users/alexander/Documents/MSc Data Science/Understanding Data and their Environment/Assignment 2/final-data/final-trainData.csv")
forecasted = import("/Users/alexander/Documents/MSc Data Science/Understanding Data and their Environment/Assignment 2/final-data/forecasted-data.csv")
```

### 1. General Distribution of Sales

```{r}
open = data[data$Open == 1,] # Only working with data for open stores
```

```{r}
stats = open %>%
  summarize(
    mean_sales = mean(Sales, na.rm = TRUE),
    sd_sales = sd(Sales, na.rm = TRUE),
    p25 = quantile(Sales, 0.25, na.rm = TRUE),
    p50 = quantile(Sales, 0.50, na.rm = TRUE),
    p75 = quantile(Sales, 0.75, na.rm = TRUE)
  )
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=3.5, fig.width=8, dpi=300}
# Create density plot
ggplot(open, aes(x = Sales)) +
  geom_density(fill = "lightblue", alpha = 0.6) +  # Density plot
  geom_vline(aes(xintercept = stats$mean_sales), color = "red", 
             linetype = "dashed", size = .5) +  # Mean  
  
  annotate("text", x = 30000, y = 0.00012, 
           label = paste0("Mean: ", round(stats$mean_sales, 0), 
                          "\nSD: ", round(stats$sd_sales, 0),
                          "\nP25: ", round(stats$p25,0),
                          "\nP50: ", round(stats$p50,0),
                          "\nP75: ", round(stats$p75,0)), size = 3) +
  labs(x = " ",
       y = " ") +
  theme_minimal()

ggsave("distribution.png")
```


### 2. Trends across time

```{r}
monthly_sales = open %>%
  mutate(Month = as.Date(cut(Date, breaks = "month"))) %>%  # Group dates by month
  group_by(Month) %>%
  summarise(Average_Sales = mean(Sales, na.rm = TRUE))  # Calculate average sales

monthly_sales$Average_Sales = round(monthly_sales$Average_Sales,0)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=8, dpi=300}
# Calculate the overall mean sales
overall_mean = mean(monthly_sales$Average_Sales, na.rm = TRUE)

# Plot with updated x-axis and mean line
ggplot(monthly_sales, aes(x = Month, y = Average_Sales)) +
  geom_line(color = "blue", size = 1) +  # Line plot
  geom_point(color = "darkred", size = 2) +  # Points for clarity
  geom_hline(yintercept = overall_mean, color = "red", linetype = "dashed", size = 0.7) +  # Horizontal mean line
  scale_x_date(date_labels = "%b %Y", date_breaks = "2 months") +  # Format x-axis as months
  scale_y_continuous(breaks = seq(0, max(monthly_sales$Average_Sales), by = 500)) +
  labs(title = " ",
       x = " ",
       y = " ") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels for readability

ggsave("trends_month.png")
```


### 3. Sales by groups


```{r echo=FALSE}
open$Promo = factor(open$Promo, levels = c(0:1), labels = c("No","Yes"))

open = open %>%
  mutate(across(c(StoreType, DayOfWeek, Assortment, Promo), as.character))

data_long = open %>%
  pivot_longer(
    cols = c(StoreType, DayOfWeek, Assortment, Promo), 
    names_to = "Category", 
    values_to = "Group"
  )

# Summarise mean sales for each group within each category
summary_data = data_long %>%
  group_by(Category, Group) %>%
  summarise(Mean_Sales = mean(Sales, na.rm = TRUE), .groups = "drop")

summary_data = summary_data %>%
  mutate(Group = fct_reorder(Group, Mean_Sales, .desc = TRUE)) 
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=8, dpi=300}
# Plot mean sales for each group within each category
ggplot(summary_data, aes(x = Group, y = Mean_Sales, fill = Group)) +
  geom_col(alpha = 0.8) +
  
  geom_text(aes(label = round(Mean_Sales, 0)), 
            vjust = -0.5, size = 3) +  # Add mean values on top
  facet_wrap(~ Category, scales = "free_x") +  # Separate graphs by Category
  scale_y_continuous(breaks = seq(0, max(monthly_sales$Average_Sales), by = 1000))+
  labs(title = " ",
       x = "",
       y = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust =.5),  # Rotate x-axis labels
        legend.position = "none")  # Remove legend since groups are clear

ggsave("trends_groups.png")
```


### 4. Holidays

```{r}
open$SchoolHoliday = factor(open$SchoolHoliday, levels = c(0:1), labels = c("No","Yes"))

open = open %>%
  mutate(across(c(StateHoliday, SchoolHoliday), as.character))

data_long = open %>%
  pivot_longer(
    cols = c(StateHoliday, SchoolHoliday), 
    names_to = "Category", 
    values_to = "Group"
  )

# Summarise mean sales for each group within each category
summary_data = data_long %>%
  group_by(Category, Group) %>%
  summarise(Mean_Sales = mean(Sales, na.rm = TRUE), .groups = "drop")

summary_data = summary_data %>%
  mutate(Group = fct_reorder(Group, Mean_Sales, .desc = TRUE)) 
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=8, dpi=300}
# Plot mean sales for each group within each category
ggplot(summary_data, aes(x = Group, y = Mean_Sales, fill = Group)) +
  geom_col(alpha = 0.8) +
  
  geom_text(aes(label = round(Mean_Sales, 0)), 
            vjust = -0.5, size = 3) +  # Add mean values on top
  facet_wrap(~ Category, scales = "free_x") +  # Separate graphs by Category
  scale_y_continuous(breaks = seq(0, max(monthly_sales$Average_Sales), by = 1000))+
  labs(title = " ",
       x = "",
       y = "") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, hjust =.5),  # Rotate x-axis labels
        legend.position = "none")  # Remove legend since groups are clear

ggsave("holiday_groups.png")
```

### 5. Bivariate relationships

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=5, fig.width=6, dpi=300}
ggplot(open, aes(x = Customers, y = Sales)) +
  geom_hex(bins = 100) +  
  scale_fill_gradient(low = "lightblue", high = "darkblue") + 
  geom_smooth(method = "gam", formula = y ~ s(x), color = "red", size = .5) +
  
  labs(title = " ",
       x = "Customers",
       y = "Sales",
       fill = "Count") +
  
  theme_minimal() +  
  
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(2, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank(),  # Remove legend title
    
    # Adjust axis title and text size
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8)      
  )

ggsave("customers_sales.png")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=5, fig.width=6, dpi=300}
ggplot(open, aes(x = CompetitionDistance, y = Sales)) +
  geom_hex(bins = 100) +  
  scale_fill_gradient(low = "lightblue", high = "darkblue") + 
  geom_smooth(method = "gam", formula = y ~ s(x), color = "red", size = .5) +
  
  labs(title = " ",
       x = "Distance of the Nearest Competitor",
       y = "Sales",
       fill = "Count") +
  
  theme_minimal() +  
  
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(2, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank(),  # Remove legend title
    
    # Adjust axis title and text size
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8)      
  )

ggsave("competitor_sales.png")
```


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=5, fig.width=6, dpi=300}
ggplot(open, aes(x = DiffTimeMonths, y = Sales)) +
  geom_hex(bins = 100) +  
  scale_fill_gradient(low = "lightblue", high = "darkblue") + 
  geom_smooth(method = "gam", formula = y ~ s(x), color = "red", size = .5) +
  
  labs(title = " ",
       x = "Closest Competitor Time",
       y = "Sales",
       fill = "Count") +
  
  theme_minimal() +  
  
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(2, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank(),  # Remove legend title
    
    # Adjust axis title and text size
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8)      
  )

ggsave("competitor_time_sales.png")
```

```{r}
promo = open[open$Promo2 == 1,]
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=5, fig.width=6, dpi=300}
ggplot(open, aes(x = DiffPromoTimeMonths, y = Sales)) +
  geom_hex(bins = 100) +  
  scale_fill_gradient(low = "lightblue", high = "darkblue") + 
  geom_smooth(method = "gam", formula = y ~ s(x), color = "red", size = .5) +
  
  labs(title = " ",
       x = "Time Participating in a Promotion",
       y = "Sales",
       fill = "Count") +
  
  theme_minimal() +  
  
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(2, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank(),  # Remove legend title
    
    # Adjust axis title and text size
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8)      
  )

ggsave("promotion_time_sales.png")
```

### 5. Model Comparison

```{r}
# For all features:
tmodel = c("OLS","Ridge","Lasso", "MLP")
rmspe = c(0.2794, 0.2778, 0.2794, 0.2211)
r2 = c(0.6912, 0.6863, 0.6912, 0.8391)

AF = as.data.frame(cbind(tmodel,rmspe, r2))
AF$nfeatures = "All Features"
```

```{r}
tmodel = c("OLS","Ridge","Lasso","MLP")
rmspe = c(0.2806, 0.2789, 0.2806, 0.2225)
r2 = c(0.6886, 0.6839, 0.6886, 0.8350)

SF = as.data.frame(cbind(tmodel,rmspe, r2))
SF$nfeatures = "Selected Features"
```

```{r}
mlModels = rbind(AF,SF)
mlModels$rmspe = as.numeric(as.character(mlModels$rmspe))
mlModels$r2 = as.numeric(as.character(mlModels$r2))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=3, dpi=300}
# Create the RMSPE plot
rmspe_plot = ggplot(mlModels, aes(x = tmodel, y = rmspe, group = nfeatures, color = nfeatures)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  geom_text_repel(aes(label = round(rmspe, 4)), size = 6, show.legend = FALSE) +  # Use ggrepel for labels
  labs(title = " ", x = " ", y = "RMSPE") +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8)
  )

# Save the plot
ggsave("rmspe.png")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=3, dpi=300}
# Create the R² plot
r2_plot = ggplot(mlModels, aes(x = tmodel, y = r2, group = nfeatures, color = nfeatures)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  geom_text_repel(aes(label = round(r2, 4)), size = 6, show.legend = FALSE) +
  labs(title = " ", x = " ", y = "R²") +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    axis.title = element_text(size = 10),   
    axis.text = element_text(size = 8))

ggsave("r2.png")

```


### 6. Forecasting Sales

```{r}
# Months:
monthly_sales_f = forecasted %>%
  mutate(Month = as.Date(cut(Date, breaks = "month"))) %>%  # Group dates by month
  group_by(Month) %>%
  summarise(Average_Sales = mean(Sales, na.rm = TRUE))  # Calculate average sales

monthly_sales_f$Average_Sales = round(monthly_sales_f$Average_Sales,0)

monthly_sales$type = "Historical Data"
monthly_sales_f$type = "Forecasted Data"
```

```{r}
# Weeks:
weekly_sales = open %>%
  mutate(Week = as.Date(cut(Date, breaks = "week"))) %>%  # Group dates by week
  group_by(Week) %>%
  summarise(Average_Sales = mean(Sales, na.rm = TRUE))  # Calculate average sales

weekly_sales$Average_Sales = round(weekly_sales$Average_Sales, 0)  # Round average sales

weekly_sales$type = "Historical Data"

# Weeks for forecasted data:
weekly_sales_f = forecasted %>%
  mutate(Week = as.Date(cut(Date, breaks = "week"))) %>%  # Group dates by week
  group_by(Week) %>%
  summarise(Average_Sales = mean(Sales, na.rm = TRUE))  # Calculate average sales

weekly_sales_f$Average_Sales = round(weekly_sales_f$Average_Sales, 0)  # Round average sales

weekly_sales_f$type = "Forecasted Data"
```

```{r}
for_month_data = rbind(monthly_sales, monthly_sales_f)
for_weeks_data = rbind(weekly_sales, weekly_sales_f)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=8, dpi=300}
# Calculate the overall mean sales
overall_mean = mean(for_month_data$Average_Sales, na.rm = TRUE)

# Plot with updated x-axis and mean line
ggplot(for_month_data, aes(x = Month, y = Average_Sales, color = type, group = 1)) +
  geom_line(size = 1) +  # Line plot with color based on type
  geom_point(size = 2) +  # Points for clarity
  geom_hline(yintercept = overall_mean, color = "red", linetype = "dashed", size = 0.7) +  # Horizontal mean line
  scale_x_date(date_labels = "%b %Y", date_breaks = "2 months") +  # Format x-axis as months
  scale_y_continuous(breaks = seq(0, max(for_month_data$Average_Sales), by = 500)) +
  scale_color_manual(values = c("Historical Data" = "blue", "Forecasted Data" = "green")) +  # Custom colors
  labs(title = " ",
       x = " ",
       y = " ") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
        legend.title = element_blank()) + # Remove legend title

  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank())

ggsave("month-forecast.png")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=8, dpi=300}
for_weeks_data = for_weeks_data[as.Date(for_weeks_data$Week) > as.Date("2014-12-29"), ]

# Calculate the overall mean sales
overall_mean <- mean(for_weeks_data$Average_Sales, na.rm = TRUE)

# Plot with updated x-axis and mean line
ggplot(for_weeks_data, aes(x = Week, y = Average_Sales, color = type, group = 1)) +
  geom_line(size = 1) +  # Line plot with color based on type
  geom_point(size = 2) +  # Points for clarity
  geom_hline(yintercept = overall_mean, color = "red", linetype = "dashed", size = 0.7) +  # Horizontal mean line
  scale_x_date(date_labels = "%b %Y", date_breaks = "2 weeks") +  # Format x-axis as weeks grouped by month
  scale_y_continuous(breaks = seq(0, max(for_weeks_data$Average_Sales, na.rm = TRUE), by = 500)) +
  scale_color_manual(values = c("Historical Data" = "blue", "Forecasted Data" = "green")) +  # Custom colors
  labs(title = " ",
       x = " ",
       y = " ") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    legend.position = "bottom", 
    legend.direction = "horizontal",
    legend.key.width = unit(1, "cm"), 
    legend.key.height = unit(0.25, "cm"),
    legend.title = element_blank()  # Remove legend title
  )

ggsave("week-forecast.png")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.height=4, fig.width=8, dpi=300}
week_mean <- mean(weekly_sales_f$Average_Sales)

ggplot(weekly_sales_f, aes(x = Week, y = Average_Sales)) +
  geom_col(alpha = 0.8) +
  
  geom_text(aes(label = round(Average_Sales, 0)), 
            vjust = -0.5, size = 3) + 
  
  geom_hline(yintercept = week_mean, color = "red", linetype = "dashed", size = 0.7) +
  
  scale_x_date(date_breaks = "1 week") + 
  
  labs(title = " ",
       x = " ",
       y = " ") +
  theme_minimal()

ggsave("week-forecast2.png")
```

